CREATE TABLE USERS (
    Id SERIAL PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Password VARCHAR(255) NOT NULL
);


CREATE TABLE PROJECTS (
    Id SERIAL PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Description TEXT NOT NULL,
    ImagePath VARCHAR(255) NOT NULL,
    CreatedAt TIMESTAMP NOT NULL DEFAULT NOW(),
    GitHubLink VARCHAR(255) NOT NULL
);

CREATE TABLE TECHNOLOGIES (
    Id SERIAL PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Description TEXT NOT NULL,
    ImagePath VARCHAR(255) NOT NULL 
);

CREATE TABLE PROJECTS_TECHNOLOGIES (
    ProjectId INT NOT NULL,
    TechnologyId INT NOT NULL,
    PRIMARY KEY (ProjectId, TechnologyId),
    FOREIGN KEY (ProjectId) REFERENCES PROJECTS(Id) ON DELETE CASCADE,
    FOREIGN KEY (TechnologyId) REFERENCES TECHNOLOGIES(Id) ON DELETE CASCADE
);